name: Docker Image CI

on:
  push:
    #branches: [ "master" ]
    #tags: ["v[0-9]+.[0-9]+.[0-9]*"]
    tags: ["v*"]

jobs:

  build:
    runs-on: "ubuntu-latest"

    steps:
    - name: "Check out the repo"
      uses: "actions/checkout@v4"
    
    - name: "docker login"
      uses: "docker/login-action@v3"
      with:
        registry: ${{env.DOCKER_REGISTRY}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: "Build, Tag, and push the Docker image - latest"
      if: ${{ github.ref_name == 'master' }}
      env:
        IMAGE_NAME: maylife/darksidetcg-backend
        IMAGE_TAG: latest
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
        
    - name: "Build, Tag, and push the Docker image - Tag"
      if: ${{ github.ref_name != 'master' }}
      env:
        IMAGE_NAME: maylife/darksidetcg-backend
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG